language: python
python:
  - "3.5" 
# command to install dependencies
install:
  - pip install fandogh-cli --upgrade
# command to run tests
script:
  - export FANDOGH_DEBUG=true
  - echo $TRAVIS_COMMIT  
  - fandogh login --username=$FANDOGH_USERNAME --password=$FANDOGH_PASSWORD
  - npm install
  - npm build
  - fandogh image publish --version=$TRAVIS_COMMIT 
  - fandogh service deploy --version=$TRAVIS_COMMIT --name=blog
