language: python
python:
  - "3.5" 
# command to install dependencies
install:
  - pip install fandogh-cli --upgrade
# command to run tests
script:
  - export FANDOGH_DEBUG=true
  - fandogh login --username=user1 --password=pass1
